name: Validate Translations

on:
  workflow_dispatch:
  push:
    branches: l10n_crowdin_translations

jobs:
  validate-translations:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          
      - name: Validate JSON files
        run: |
          echo "Validating JSON files..."
          
          # Validate source file
          if ! jq empty src/main/resources/assets/createchocolatefactory/lang/en_us.json; then
            echo "❌ Invalid JSON in en_us.json"
            exit 1
          fi
          
          # Validate translation files
          for file in src/crowdin/resources/assets/createchocolatefactory/lang/*.json; do
            if [ -f "$file" ]; then
              if ! jq empty "$file"; then
                echo "❌ Invalid JSON in $file"
                exit 1
              fi
              echo "✅ Validated $file"
            fi
          done
          
      - name: Check for missing translations
        run: |
          echo "Checking for missing translations..."
          
          # Get all keys from source file
          source_keys=$(jq -r 'keys[]' src/main/resources/assets/createchocolatefactory/lang/en_us.json | sort)
          
          # Check each translation file
          for file in src/crowdin/resources/assets/createchocolatefactory/lang/*.json; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              echo "Checking $filename..."
              
              # Get keys from translation file
              translation_keys=$(jq -r 'keys[]' "$file" | sort)
              
              # Find missing keys
              missing_keys=$(comm -23 <(echo "$source_keys") <(echo "$translation_keys"))
              
              if [ -n "$missing_keys" ]; then
                echo "❌ Missing translations in $filename:"
                echo "$missing_keys"
                exit 1
              else
                echo "✅ All translations present in $filename"
              fi
            fi
          done
          
      - name: Check for extra translations
        run: |
          echo "Checking for extra translations..."
          
          # Get all keys from source file
          source_keys=$(jq -r 'keys[]' src/main/resources/assets/createchocolatefactory/lang/en_us.json | sort)
          
          # Check each translation file
          for file in src/crowdin/resources/assets/createchocolatefactory/lang/*.json; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              
              # Get keys from translation file
              translation_keys=$(jq -r 'keys[]' "$file" | sort)
              
              # Find extra keys
              extra_keys=$(comm -13 <(echo "$source_keys") <(echo "$translation_keys"))
              
              if [ -n "$extra_keys" ]; then
                echo "⚠️  Extra translations found in $filename:"
                echo "$extra_keys"
                echo "These will be removed during sync"
              fi
            fi
          done 